version: '3.8'

services:
  milestone-tracker-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: milestone_tracker_api
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Telegram_BotToken=${BOT_TOKEN}
      - Telegram_WebhookUrl=${WEBHOOK_URL}
      - Database_ConnectionString=${DB_STRING}
    depends_on:
      - postgres
    networks:
      - milestone_network

  postgres:
    image: postgres:15-alpine
    container_name: milestone_tracker_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: milestones
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d milestones" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - milestone_network

volumes:
  pgdata:

networks:
  milestone_network:
    driver: bridge
