// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MilestoneTracker.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MilestoneTracker.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MilestoneTracker.Domain.Entities.Child", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<string>("PhotoFileId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("photo_file_id");

                    b.HasKey("Id")
                        .HasName("pk_children");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_children_parent_id");

                    b.ToTable("children", (string)null);
                });

            modelBuilder.Entity("MilestoneTracker.Domain.Entities.Milestones.Milestone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<int>("ChildId")
                        .HasColumnType("integer")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_milestones");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_milestones_category");

                    b.HasIndex("ChildId")
                        .HasDatabaseName("ix_milestones_child_id");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("ix_milestones_creator_id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_milestones_occurred_at");

                    b.ToTable("milestones", (string)null);
                });

            modelBuilder.Entity("MilestoneTracker.Domain.Entities.Milestones.MilestoneMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Caption")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("caption");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_id");

                    b.Property<int>("MilestoneId")
                        .HasColumnType("integer")
                        .HasColumnName("milestone_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("pk_milestone_media");

                    b.HasIndex("MilestoneId")
                        .HasDatabaseName("ix_milestone_media_milestone_id");

                    b.ToTable("milestone_media", (string)null);
                });

            modelBuilder.Entity("MilestoneTracker.Domain.Entities.Parent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_parents");

                    b.HasIndex("ChatId")
                        .IsUnique()
                        .HasDatabaseName("ix_parents_chat_id");

                    b.ToTable("parents", (string)null);
                });

            modelBuilder.Entity("MilestoneTracker.Domain.Entities.UserState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<string>("StateData")
                        .HasColumnType("jsonb")
                        .HasColumnName("state_data");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_user_states");

                    b.HasIndex("ChatId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_states_chat_id");

                    b.ToTable("user_states", (string)null);
                });

            modelBuilder.Entity("MilestoneTracker.Domain.Entities.Child", b =>
                {
                    b.HasOne("MilestoneTracker.Domain.Entities.Parent", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_children_parents_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MilestoneTracker.Domain.Entities.Milestones.Milestone", b =>
                {
                    b.HasOne("MilestoneTracker.Domain.Entities.Child", "Child")
                        .WithMany("Milestones")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_milestones_children_child_id");

                    b.HasOne("MilestoneTracker.Domain.Entities.Parent", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_milestones_parents_creator_id");

                    b.Navigation("Child");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("MilestoneTracker.Domain.Entities.Milestones.MilestoneMedia", b =>
                {
                    b.HasOne("MilestoneTracker.Domain.Entities.Milestones.Milestone", null)
                        .WithMany("MediaFiles")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_milestone_media_milestones_milestone_id");
                });

            modelBuilder.Entity("MilestoneTracker.Domain.Entities.Child", b =>
                {
                    b.Navigation("Milestones");
                });

            modelBuilder.Entity("MilestoneTracker.Domain.Entities.Milestones.Milestone", b =>
                {
                    b.Navigation("MediaFiles");
                });

            modelBuilder.Entity("MilestoneTracker.Domain.Entities.Parent", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
