// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MilestoneTracker.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MilestoneTracker.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260501075721_SoftDeletionFieldsForMilestone")]
    partial class SoftDeletionFieldsForMilestone
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChildParent", b =>
                {
                    b.Property<int>("ChildrenId")
                        .HasColumnType("integer")
                        .HasColumnName("children_id");

                    b.Property<int>("ParentsId")
                        .HasColumnType("integer")
                        .HasColumnName("parents_id");

                    b.HasKey("ChildrenId", "ParentsId")
                        .HasName("pk_child_parent");

                    b.HasIndex("ParentsId")
                        .HasDatabaseName("ix_child_parent_parents_id");

                    b.ToTable("child_parent", (string)null);
                });

            modelBuilder.Entity("MilestoneTracker.Domain.Entities.Child", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PhotoFileId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("photo_file_id");

                    b.HasKey("Id")
                        .HasName("pk_children");

                    b.ToTable("children", (string)null);
                });

            modelBuilder.Entity("MilestoneTracker.Domain.Entities.ChildAccessToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChildId")
                        .HasColumnType("integer")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer")
                        .HasColumnName("creator_id");

                    b.Property<int>("CurrentUses")
                        .HasColumnType("integer")
                        .HasColumnName("current_uses");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<int>("MaxUses")
                        .HasColumnType("integer")
                        .HasColumnName("max_uses");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<int?>("UsedByParentId")
                        .HasColumnType("integer")
                        .HasColumnName("used_by_parent_id");

                    b.HasKey("Id")
                        .HasName("pk_access_tokens");

                    b.HasIndex("ChildId")
                        .HasDatabaseName("ix_access_tokens_child_id");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("ix_access_tokens_creator_id");

                    b.HasIndex("IsUsed")
                        .HasDatabaseName("ix_access_tokens_is_used");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_access_tokens_token");

                    b.HasIndex("UsedByParentId")
                        .HasDatabaseName("ix_access_tokens_used_by_parent_id");

                    b.ToTable("access_tokens", (string)null);
                });

            modelBuilder.Entity("MilestoneTracker.Domain.Entities.Milestones.Milestone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<int>("ChildId")
                        .HasColumnType("integer")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer")
                        .HasColumnName("creator_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_milestones");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_milestones_category");

                    b.HasIndex("ChildId")
                        .HasDatabaseName("ix_milestones_child_id");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("ix_milestones_creator_id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_milestones_occurred_at");

                    b.ToTable("milestones", (string)null);
                });

            modelBuilder.Entity("MilestoneTracker.Domain.Entities.Milestones.MilestoneMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Caption")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("caption");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_id");

                    b.Property<int>("MilestoneId")
                        .HasColumnType("integer")
                        .HasColumnName("milestone_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("pk_milestone_media");

                    b.HasIndex("MilestoneId")
                        .HasDatabaseName("ix_milestone_media_milestone_id");

                    b.ToTable("milestone_media", (string)null);
                });

            modelBuilder.Entity("MilestoneTracker.Domain.Entities.Parent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_parents");

                    b.HasIndex("ChatId")
                        .IsUnique()
                        .HasDatabaseName("ix_parents_chat_id");

                    b.ToTable("parents", (string)null);
                });

            modelBuilder.Entity("MilestoneTracker.Domain.Entities.UserState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<string>("StateData")
                        .HasColumnType("jsonb")
                        .HasColumnName("state_data");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_user_states");

                    b.HasIndex("ChatId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_states_chat_id");

                    b.ToTable("user_states", (string)null);
                });

            modelBuilder.Entity("ChildParent", b =>
                {
                    b.HasOne("MilestoneTracker.Domain.Entities.Child", null)
                        .WithMany()
                        .HasForeignKey("ChildrenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_child_parent_children_children_id");

                    b.HasOne("MilestoneTracker.Domain.Entities.Parent", null)
                        .WithMany()
                        .HasForeignKey("ParentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_child_parent_parents_parents_id");
                });

            modelBuilder.Entity("MilestoneTracker.Domain.Entities.ChildAccessToken", b =>
                {
                    b.HasOne("MilestoneTracker.Domain.Entities.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_access_tokens_children_child_id");

                    b.HasOne("MilestoneTracker.Domain.Entities.Parent", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_access_tokens_parents_creator_id");

                    b.HasOne("MilestoneTracker.Domain.Entities.Parent", "UsedByParent")
                        .WithMany()
                        .HasForeignKey("UsedByParentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_access_tokens_parents_used_by_parent_id");

                    b.Navigation("Child");

                    b.Navigation("Creator");

                    b.Navigation("UsedByParent");
                });

            modelBuilder.Entity("MilestoneTracker.Domain.Entities.Milestones.Milestone", b =>
                {
                    b.HasOne("MilestoneTracker.Domain.Entities.Child", "Child")
                        .WithMany("Milestones")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_milestones_children_child_id");

                    b.HasOne("MilestoneTracker.Domain.Entities.Parent", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_milestones_parents_creator_id");

                    b.Navigation("Child");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("MilestoneTracker.Domain.Entities.Milestones.MilestoneMedia", b =>
                {
                    b.HasOne("MilestoneTracker.Domain.Entities.Milestones.Milestone", null)
                        .WithMany("MediaFiles")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_milestone_media_milestones_milestone_id");
                });

            modelBuilder.Entity("MilestoneTracker.Domain.Entities.Child", b =>
                {
                    b.Navigation("Milestones");
                });

            modelBuilder.Entity("MilestoneTracker.Domain.Entities.Milestones.Milestone", b =>
                {
                    b.Navigation("MediaFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
